export const CHANGE_ROUTE = 'CHANGE_ROUTE';

export const FETCH_SESSION_LIKES_SUCCESS = 'FETCH_SESSION_LIKES_SUCCESS';
export const FETCH_SESSION_USER_SUCCESS = 'FETCH_SESSION_USER_SUCCESS';

export const FETCH_ACCOUNTLIST_SUCCESS = 'FETCH_ACCOUNTLIST_SUCCESS';

export const FETCH_GROUPLIST_REQUEST = 'FETCH_GROUPLIST_REQUEST';
export const FETCH_GROUPLIST_SUCCESS = 'FETCH_GROUPLIST_SUCCESS';
export const FETCH_GROUPLIST_FAILED = 'FETCH_GROUPLIST_FAILED';

export const SET_FAVORITEGROUP_SUCCESS = 'SET_FAVORITEGROUP_SUCCESS';
export const SET_FAVORITEGROUP_FAILED = 'SET_FAVORITEGROUP_FAILED';

export const TOGGLE_LIKE = 'TOGGLE_LIKE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const SAVEPROFILE_REQUEST = 'SAVEPROFILE_REQUEST';
export const SAVEPROFILE_SUCCESS = 'SAVEPROFILE_SUCCESS';
export const SAVEPROFILE_FAILED = 'SAVEPROFILE_FAILED';

export const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_FAILED = 'CHANGEPASSWORD_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const ADDING_NEW_GROUP = 'ADDING_NEW_GROUP';
export const CLOSING_NEW_GROUP = 'CLOSING_NEW_GROUP';

export const ADD_NEWGROUP_REQUEST = 'ADD_NEWGROUP_REQUEST';
export const ADD_NEWGROUP_SUCCESS = 'ADD_NEWGROUP_SUCCESS';
export const ADD_NEWGROUP_FAILED = 'ADD_NEWGROUP_FAILED';

export const FETCH_MESSAGE_REQUEST = 'FETCH_MESSAGE_REQUEST';
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';
export const FETCH_MESSAGE_FAILED = 'FETCH_MESSAGE_FAILED';

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const GOT_UNREADMESSAGE = 'GOT_UNREADMESSAGE';

export const NEW_TOAST = 'NEW_TOAST';
export const DISMISS_TOAST = 'DISMISS_TOAST';

export const INCOMING_USER = 'INCOMING_USER';
export const OUTGOING_USER = 'OUTGOING_USER';
export const ONLINE_USERS = 'ONLINE_USERS';